version: '3.7'
services:

    database:
        container_name: database
        image: 'mysql:5.7'
        volumes:
            - ./data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'
        networks:
            - appnet

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
        networks:
            - appnet

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app/:/var/www/app
        depends_on:
            - database
        networks:
            - appnet

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8000:8000'
        depends_on:
            - database
        networks:
            - appnet

networks:
    appnet:
        driver: 'bridge'
